CREATE DATABASE faculdade1;
USE faculdade1;

CREATE TABLE usuarios (
id INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(100) NOT NULL,
sobrenome VARCHAR(100) NOT NULL,
email VARCHAR(150) NOT NULL UNIQUE,
curso VARCHAR(50) NOT NULL,
nota_atividade INT NOT NULL DEFAULT 0,
nota_prova INT NOT NULL DEFAULT 0,
nota_final INT NOT NULL DEFAULT 0,
data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);